ARG REGISTRY=blackgolfer
FROM ${REGISTRY}/qi-doc-markdown:latest

LABEL description="Container for use with VS"

# setting up user
ARG USERNAME=user-name-goes-here
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd -f --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# for installing security prerequisit for vscode devcontainer
RUN apt-get update && apt-get install -y openssh-server rsync zip clang-format git curl

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************
# clean up
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get clean

# Cleanup
# TODO: remove build helpers/packages
RUN rm -rf /bin-setup

# setting up system for vscode devcontainer
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    ssh-keygen -A

EXPOSE 22 

USER $USERNAME
WORKDIR /home/$USERNAME
# terminal colors with xterm
ENV TERM xterm
# set the zsh theme
#ENV ZSH_THEME agnoster
RUN wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O - | zsh || true
RUN mkdir -p "$HOME/.zsh" \
    && git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
ENV LANG="C.UTF-8"
WORKDIR /home/$USERNAME/docs
ADD ./.zshrc /home/$USERNAME
CMD ["/usr/sbin/sshd", "-D"]