var currLink="",linkid=0,linkarray="home,y10,ysm,ysearch,ybuzz,jockey,comic,geopark,musicbattle,arena,team,more".split(","),posarray=[],maxpage=linkarray.length,scrollTop=0,logoBlack=true,ysmloaded="",ybuzzloaded="",ysearchloaded="",y10loaded="",hkacloaded="",currswf="",ismobile=false,jgamestarted=true,jcount=0,tempSpeed=0,prevForce=0,jscore=0;function plusone(){jcount++;$("#jcount").html(jcount)}
function jgamestart(){jscore=prevForce=tempSpeed=jcount=0;$("#jcount").html("Click now!");jgamestarted=true;$("#joc3").everyTime(1E3,function(){tempSpeed=Math.floor(Math.random()*100)+20;var a=jcount-prevForce;prevForce=jcount;a*=20;tempSpeed>a?jscore-=tempSpeed-a:jscore+=a;$("#joc3").animate({"margin-left":jscore+"px"},1E3);jscore<-500&&($("#jcount").html("Game over"),jend());jscore>500&&($("#jcount").html("You win!"),jend())})}
function jend(){jgamestarted==true&&($("#jtotalclick").load("http://whyinteractive.com/showreel/jclick.php?action="+jcount+"#value"),jscore=prevForce=tempSpeed=jcount=0,jgamestarted=false,$("#joc3").stop(true).stopTime(),$("#joc3").stop().animate({"margin-left":"0px"},1E3))}jQuery(function(a){a.easing.easeOutExpo=function(a,c,d,e,f){return e*((c=c/f-1)*c*(2.70158*c+1.70158)+1)+d}});
$(document).ready(function(){CalculateWindow();$.flash.available||$(".hideswf").css("display","none");if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i))ismobile=true,$(".mainNavGroup div").css("position","absolute"),$("#up").css("position","absolute"),$("#down").css("position","absolute"),$("#down").css("top",scrollTop+$(window).height()-30+"px");scrollTop=$(window).scrollTop();$("#menuHolder").hover(function(){showMenu()},
function(){hideMenu()});$("#up").click(function(){prevPage()});$("#down").click(function(){nextPage()});$("#jockeybtn").hover(function(){jgamestart()},function(){$("#jcount").html("");jend()});$("#jockeybtn").click(function(){jgamestarted&&plusone()});hideMenu();$(window).scroll(function(){scrollTop=$(this).scrollTop();scrollTop<posarray[1]-50&&updateSection(linkarray[0]);for(i=1;i<posarray.length-2;i++)scrollTop>posarray[i]-50&&scrollTop<posarray[i+1]-50&&updateSection(linkarray[i]);scrollTop>posarray[10]-
50&&scrollTop<posarray[11]-500&&updateSection(linkarray[10]);scrollTop>posarray[11]-500&&updateSection(linkarray[11]);ismobile||movebg();ismobile&&($("#home").css("top",scrollTop+"px"),$("#up").css("top",scrollTop+"px"),$("#down").css("top",scrollTop+$(window).height()-30+"px"));$("#debug").html("pY:"+scrollTop)});scrollTop=0;$.scrollTo(0,500);$("#b"+currLink).css("color","");$("#bhome").css("color","#333");$("#menuHL").html("Home");currLink="home";changeLogo("black");updateArrow();$("#jtotalclick").load("http://whyinteractive.com/showreel/jclick.php#value")});
function movebg(){(scrollTop<=posarray[2]+408||scrollTop<=posarray[5]+1E3)&&logoBlack==false&&changeLogo("black");(scrollTop>posarray[2]+408&&scrollTop<posarray[3]-20||scrollTop>posarray[4]+700&&scrollTop<posarray[6]-150)&&logoBlack==true&&changeLogo("white");scrollTop<posarray[1]&&$("#home1").css("margin-top",posarray[0]-scrollTop+"px");scrollTop>posarray[0]&&scrollTop<posarray[2]&&($("#y101").css("margin-top",(posarray[1]-scrollTop)/4+"px"),$("#y102").css("margin-top",posarray[1]-scrollTop+"px"));
scrollTop>posarray[1]&&scrollTop<posarray[3]&&$("#ysm1").css("margin-top",posarray[2]-scrollTop+"px");scrollTop>posarray[2]&&scrollTop<posarray[4]&&($("#ys1").css("margin-top",posarray[3]-scrollTop+"px"),$("#ystop").css("height",posarray[3]-scrollTop+"px"));scrollTop>posarray[3]&&scrollTop<posarray[5]&&($("#bz1").css("margin-top",posarray[4]-scrollTop+"px"),$("#bz2").css("margin-top",(posarray[4]-scrollTop)/0.5+"px"),$("#bz3").css("margin-top",(posarray[4]-scrollTop)/4+"px"));scrollTop>posarray[4]&&
scrollTop<posarray[6]&&($("#jstop").css("height",posarray[5]+200-scrollTop+"px"),$("#joc1").css("margin-top",posarray[5]-scrollTop+"px"),$("#joc2").css("margin-top",(posarray[5]-scrollTop)/4+"px"));scrollTop>posarray[5]&&scrollTop<posarray[7]&&($("#cstop").css("height",posarray[6]+200-scrollTop+"px"),$("#com1").css("margin-top",posarray[6]-scrollTop+"px"),$("#com2").css("margin-top",(posarray[6]-scrollTop)/4+"px"));scrollTop>posarray[5]&&scrollTop<posarray[8]&&($("#g1").css("margin-top",posarray[7]-
scrollTop+"px"),$("#g3").css("margin-top",(posarray[7]-scrollTop)/0.5+"px"),$("#g0").css("margin-top",(posarray[7]-scrollTop)/4+"px"));scrollTop>posarray[6]&&scrollTop<posarray[9]&&($("#mb4").css("margin-top",(posarray[8]-scrollTop)/8+"px"),$("#mb5").css("margin-top",posarray[8]-scrollTop+"px"));scrollTop>posarray[7]&&scrollTop<posarray[10]&&($("#arena1").css("margin-top",posarray[9]-scrollTop+"px"),$("#arena2").css("margin-top",(posarray[9]-scrollTop)/4+"px"))}
window.onload=function(){$("#loader").fadeOut("slow");CalculateWindow()};$(window).bind("resize",function(){CalculateWindow()});function changeLogo(a){a=="white"&&($("#whyLogo").html('<img src="images/whyLogo_w.png">'),$("#menuHL").css("color","#fff"),logoBlack=false);a=="black"&&($("#whyLogo").html('<img src="images/whyLogo.png">'),$("#menuHL").css("color","#333"),logoBlack=true)}
function goSection(a){currswf!=""&&unloadswf(currswf);$("#menuHL").html($("#b"+a).html());ismobile?$.scrollTo("#"+a,1500,{axis:"y"}):$.scrollTo("#"+a,2E3,{axis:"y",easing:"easeOutExpo"})}
function loadswf(a){$.flash.available?(a=="buzz"?(ybuzzloaded=$("#ybuzzholder").html(),$("#ybuzzholder").flash({swf:"swf/buzzvdo.swf",height:"100%",width:"100%"})):a=="ysearch"?(ysearchloaded=$("#ysearchswf").html(),$("#ysearchswf").flash({swf:"swf/ysearch.swf",height:"100%",width:"100%"})):a=="ysm"?(ysmloaded=$("#ysmholder").html(),$("#ysmholder").flash({swf:"swf/ysm_game.swf",height:600,width:1200,wmode:"transparent"})):a=="y10"?(y10loaded=$("#y10holder").html(),$("#y10holder").flash({swf:"swf/y10.swf",
height:620,width:"100%",wmode:"transparent"})):a=="hkac"&&(hkacloaded=$("#hkacholder").html(),$("#hkacholder").flash({swf:"swf/hkac.swf",height:1E3,width:"100%",wmode:"transparent"})),currswf=a):alert("Sorry, your device doesn't support Flash.")}
function unloadswf(a){a=="buzz"?($("#ybuzzholder").flash().remove(),$("#ybuzzholder").html(ybuzzloaded),ybuzzloaded=""):a=="ysearch"?($("#ysearchswf").flash().remove(),$("#ysearchswf").html(ysearchloaded),ysearchloaded=""):a=="ysm"?($("#ysmholder").flash().remove(),$("#ysmholder").html(ysmloaded),ysmloaded=""):a=="y10"?($("#y10holder").flash().remove(),$("#y10holder").html(y10loaded),y10loaded=""):a=="hkac"&&($("#hkacholder").flash().remove(),$("#hkacholder").html(hkacloaded),hkacloaded="");currswf=
""}
function updateSection(a){a!=currLink&&(currswf!=""&&unloadswf(currswf),ismobile?($("#home").css("top",scrollTop+"px"),$("#up").css("top",scrollTop+"px"),$("#down").css("top",scrollTop+$(window).height()-30+"px")):(a=="geopark"?$("#g2").everyTime(10,function(){$("#g2").animate({top:"100px"},1400).animate({top:"150px"},1600)}):a!="comic"&&$("#g2").stop(true).stopTime(),a=="arena"?$("#arena1").everyTime(10,function(){$("#arena1").animate({top:"100px"},1400).animate({top:"50px"},1600)}):a!="musicbattle"&&$("#arena1").stop(true).stopTime(),
a=="musicbattle"?$("#mb1").everyTime(10,function(){$("#mb1").animate({width:"940px",top:"50px",left:"0px"},400).animate({width:"800px",top:"100px",left:"50px"},370);$("#mb2").animate({width:"940px",top:"-50px",left:"0px"},670).animate({width:"800px",top:"0px",left:"50px"},840);$("#mb3").animate({width:"300px",top:"120px",left:"480px"},670).animate({width:"456px",top:"0px",left:"400px"},840)}):a!="geopark"&&($("#mb1").stop(true).stopTime(),$("#mb2").stop(true).stopTime(),$("#mb3").stop(true).stopTime())),
$("#b"+currLink).css("color",""),$("#b"+a).css("color","#333"),$("#menuHL").html($("#b"+a).html()),currLink=a,updateArrow(),changeLogo("black"))}function nextPage(){var a=getCurrLink();a<maxpage&&goSection(linkarray[a+1])}function prevPage(){var a=getCurrLink();a>0&&goSection(linkarray[a-1])}function updateArrow(){var a=getCurrLink();a<=0?$("#up").fadeOut():$("#up").fadeIn();a>=maxpage-1?$("#down").fadeOut():$("#down").fadeIn()}
function getCurrLink(){var a;for(i=0;i<linkarray.length;i++)if(linkarray[i]==currLink)return a=i}function showMenu(){$("#menuHL").css("display","none");$("#mainmenu").css("display","")}function hideMenu(){$("#menuHL").delay(100).css("display","");$("#mainmenu").css("display","none")}
function CalculateWindow(){var a=$(window).width(),b=$(window).height();if(a>975){$("#loader").css("width",a+"px");$("#wrapper").css("left",(a-975)/2+"px");$(".y10").css("margin-left","-"+(a-975)/2+"px");$("#ysmbottom").css("margin-left","-"+(a-975)/2+"px");var c=(b+50)*16/9,d=b+50;c<a&&(c=a+50,d=(a+50)*9/16);$("#ybuzzholder").css("width",c+"px");$("#ybuzzholder").css("height",d+"px");$("#ybuzz").css("margin-left","-"+(c-975)/2+"px");$(".ysearch").css("margin-left","-"+(a-975)/2+"px");$("#ysearch").css("height",
b+"px");$(".comic").css("margin-left","-"+(a-975)/2+"px");$(".jockey").css("margin-left","-"+(a-975)/2+"px");$("#jimage").css("margin-left","-"+(1600-a)/2+"px")}b>600?(a=(b-600)/2+20,$(".addpad").css("margin-top",a+"px"),$(".addpad").css("padding-bottom",a+"px"),$("#jimage").css("padding-top",(b-600)/2+"px"),$("#joc3").css("top",(b-600)/2+228+"px"),$("#jothers").css("top",(b-600)/2+400+"px")):($(".addpad").css("margin-top","0px"),$(".addpad").css("padding-bottom","0px"),$("#jimage").css("padding-top",
"0px"),$("#joc3").css("top","228px"),$("#jothers").css("top","400px"));for(i=0;i<maxpage;i++)a=$("#"+linkarray[i]).offset(),posarray[i]=a.top;$("#bigwrapper").css("height",posarray[10]+1600+b+"px")};
